export type PhaseOneRoute = {
  route: string;
  title: string;
  pageType: string;
  purpose: string;
};

export const phaseOneRoutes: PhaseOneRoute[] = [
  { route: "/app/dashboard", title: "Dashboard", pageType: "Workspace", purpose: "Main operational dashboard." },
  { route: "/app/search", title: "Global Search", pageType: "Workspace", purpose: "Global search across operational records." },
  { route: "/app/notifications", title: "Notifications", pageType: "Workspace", purpose: "User notifications and operational alerts." },
  { route: "/app/reception", title: "Reception Workspace", pageType: "Workspace", purpose: "Reception operator workspace." },
  { route: "/app/reception/intake/new", title: "New Intake", pageType: "Create", purpose: "New patient or new visit intake." },
  { route: "/app/reception/queue", title: "Reception Queue", pageType: "Workspace", purpose: "Reception queue control." },
  { route: "/app/reception/check-in", title: "Check-in", pageType: "Workspace", purpose: "Appointment arrivals and check-in." },
  { route: "/app/reception/walk-ins", title: "Walk-ins", pageType: "Workspace", purpose: "Walk-in patient flow." },
  { route: "/app/reception/patient-search", title: "Patient Search", pageType: "Workspace", purpose: "Fast patient lookup." },
  { route: "/app/patients", title: "Patients", pageType: "List", purpose: "Patient search and list." },
  { route: "/app/patients/new", title: "Create Patient", pageType: "Create", purpose: "Create patient." },
  { route: "/app/patients/[id]", title: "Patient Detail", pageType: "Detail", purpose: "Patient profile default overview." },
  { route: "/app/patients/[id]/overview", title: "Patient Overview", pageType: "Detail", purpose: "Patient overview." },
  { route: "/app/patients/[id]/visits", title: "Patient Visits", pageType: "List", purpose: "Patient visit history." },
  { route: "/app/patients/[id]/medical-record", title: "Medical Record", pageType: "Detail", purpose: "Patient medical record summary." },
  { route: "/app/patients/[id]/lab-results", title: "Lab Results", pageType: "List", purpose: "Patient lab result history." },
  { route: "/app/patients/[id]/radiology", title: "Radiology History", pageType: "List", purpose: "Patient radiology result history." },
  { route: "/app/patients/[id]/invoices", title: "Patient Invoices", pageType: "List", purpose: "Patient invoice and payment history." },
  { route: "/app/patients/[id]/documents", title: "Patient Documents", pageType: "List", purpose: "Patient documents." },
  { route: "/app/patients/[id]/activity", title: "Patient Activity", pageType: "List", purpose: "Patient activity timeline." },
  { route: "/app/patients/[id]/edit", title: "Edit Patient", pageType: "Edit", purpose: "Edit patient profile." },
  { route: "/app/appointments", title: "Appointments", pageType: "Workspace", purpose: "Scheduling overview." },
  { route: "/app/appointments/calendar", title: "Appointment Calendar", pageType: "Workspace", purpose: "Calendar view." },
  { route: "/app/appointments/list", title: "Appointment List", pageType: "List", purpose: "Appointment list." },
  { route: "/app/appointments/new", title: "Create Appointment", pageType: "Create", purpose: "Create appointment." },
  { route: "/app/appointments/[id]", title: "Appointment Detail", pageType: "Detail", purpose: "Appointment detail." },
  { route: "/app/appointments/[id]/edit", title: "Edit Appointment", pageType: "Edit", purpose: "Edit appointment." },
  { route: "/app/visits", title: "Visits", pageType: "List", purpose: "Visit list and filters." },
  { route: "/app/visits/new", title: "Create Visit", pageType: "Create", purpose: "Create new visit." },
  { route: "/app/visits/[id]", title: "Visit Detail", pageType: "Detail", purpose: "Visit detail default workspace." },
  { route: "/app/visits/[id]/clinical", title: "Visit Clinical", pageType: "Detail", purpose: "Clinical section." },
  { route: "/app/visits/[id]/orders", title: "Visit Orders", pageType: "Detail", purpose: "Orders section." },
  { route: "/app/visits/[id]/lab", title: "Visit Lab", pageType: "Detail", purpose: "Linked lab orders and results." },
  { route: "/app/visits/[id]/radiology", title: "Visit Radiology", pageType: "Detail", purpose: "Linked radiology orders and results." },
  { route: "/app/visits/[id]/billing", title: "Visit Billing", pageType: "Detail", purpose: "Billing summary." },
  { route: "/app/visits/[id]/documents", title: "Visit Documents", pageType: "Detail", purpose: "Visit documents." },
  { route: "/app/visits/[id]/timeline", title: "Visit Timeline", pageType: "Detail", purpose: "Visit timeline." },
  { route: "/app/doctor", title: "Doctor Workspace", pageType: "Workspace", purpose: "Doctor main workspace." },
  { route: "/app/doctor/queue", title: "Doctor Queue", pageType: "Workspace", purpose: "Doctor waiting queue." },
  { route: "/app/doctor/active", title: "Active Consultations", pageType: "Workspace", purpose: "Active consultations." },
  { route: "/app/doctor/reviews", title: "Doctor Reviews", pageType: "Workspace", purpose: "Lab and radiology review queue." },
  { route: "/app/doctor/completed", title: "Completed Consultations", pageType: "List", purpose: "Completed consultations." },
  { route: "/app/doctor/visits/[id]", title: "Doctor Visit Detail", pageType: "Detail", purpose: "Doctor visit detail." },
  { route: "/app/lab", title: "Lab Workspace", pageType: "Workspace", purpose: "Lab main workspace." },
  { route: "/app/lab/orders", title: "Lab Orders", pageType: "List", purpose: "Lab orders list." },
  { route: "/app/lab/orders/[id]", title: "Lab Order Detail", pageType: "Detail", purpose: "Lab order detail." },
  { route: "/app/lab/sample-collection", title: "Sample Collection", pageType: "Workspace", purpose: "Sample collection queue." },
  { route: "/app/lab/processing", title: "Lab Processing", pageType: "Workspace", purpose: "Processing queue." },
  { route: "/app/lab/result-entry", title: "Result Entry", pageType: "Workspace", purpose: "Result entry queue." },
  { route: "/app/lab/results", title: "Lab Results", pageType: "List", purpose: "Lab results." },
  { route: "/app/lab/reports", title: "Lab Reports", pageType: "Report", purpose: "Lab reports." },
  { route: "/app/lab/equipment", title: "Lab Equipment", pageType: "List", purpose: "Lab equipment status." },
  { route: "/app/cashier", title: "Cashier Workspace", pageType: "Workspace", purpose: "Cashier main workspace." },
  { route: "/app/cashier/invoices", title: "Invoices", pageType: "List", purpose: "Invoice list." },
  { route: "/app/cashier/invoices/[id]", title: "Invoice Detail", pageType: "Detail", purpose: "Invoice detail and payment." },
  { route: "/app/cashier/payments", title: "Payments", pageType: "List", purpose: "Payment list." },
  { route: "/app/cashier/refunds", title: "Refunds", pageType: "Workspace", purpose: "Refund flow." },
  { route: "/app/cashier/debts", title: "Debtors", pageType: "List", purpose: "Debtors." },
  { route: "/app/cashier/shift-close", title: "Shift Close", pageType: "Workspace", purpose: "Close cashier shift." },
  { route: "/app/admin", title: "Admin", pageType: "Workspace", purpose: "Admin settings overview." },
  { route: "/app/admin/users", title: "Users", pageType: "Settings", purpose: "User management." },
  { route: "/app/admin/roles", title: "Roles", pageType: "Settings", purpose: "Role management." },
  { route: "/app/admin/permissions", title: "Permissions", pageType: "Settings", purpose: "Permission management." },
  { route: "/app/admin/branches", title: "Branches", pageType: "Settings", purpose: "Branch management." },
  { route: "/app/admin/departments", title: "Departments", pageType: "Settings", purpose: "Department management." },
  { route: "/app/admin/rooms", title: "Rooms", pageType: "Settings", purpose: "Room management." },
  { route: "/app/admin/services", title: "Services", pageType: "Settings", purpose: "Service catalog." },
  { route: "/app/admin/pricelist", title: "Price List", pageType: "Settings", purpose: "Price list." },
  { route: "/app/admin/doctors", title: "Doctors", pageType: "Settings", purpose: "Doctor settings." },
  { route: "/app/admin/lab-tests", title: "Lab Tests", pageType: "Settings", purpose: "Lab test catalog." },
  { route: "/app/admin/workflows", title: "Workflows", pageType: "Settings", purpose: "Workflow settings." },
];

export function getPhaseOneRoute(route: string): PhaseOneRoute {
  return phaseOneRoutes.find((item) => item.route === route) ?? {
    route,
    title: "Phase 1 Route",
    pageType: "Placeholder",
    purpose: "Documented Phase 1 route placeholder.",
  };
}
